/* Approved Gatehouse presentation; shared Common Gear retains all values and actions. */
/* exported renderGatehouseGearScreen */
const GATEHOUSE_OFFICER_ART = "assets/optimized/gatehouse-defensive-commander-still-400x800-91bb0b3d00ee.webp";
const formatGatehouseGearNumber = value => Math.floor(Number(value) || 0).toLocaleString("en-US");
const formatGatehouseGearPercent = value => Number(value).toFixed(2);
const getGatehouseGearShortName=value=>value.replace("Defensive Commander's ","");
const renderGatehouseGearArt=(src,alt="")=>`<img src="${escapeHtml(src)}" alt="${escapeHtml(alt)}" draggable="false" onerror="this.hidden=true">`;
const GATEHOUSE_GEAR_ICONS={
  gatehouse:"<path fill=\"currentColor\" fill-opacity=\".12\" d=\"M3 28V8h3V4h4v4h3V5h6v3h3V4h4v4h3v20Z\"/><path fill=\"currentColor\" fill-opacity=\".25\" stroke=\"none\" d=\"M25 9h4v19h-4Z\"/><path d=\"M11 9v18m10-18v18M3 17h8m10 0h8\"/><path fill=\"currentColor\" fill-opacity=\".12\" d=\"M12 28V18a4 4 0 0 1 8 0v10Z\"/><path d=\"M14 17v11m4-11v11m-6-7h8m-8 4h8\"/><path stroke-width=\".9\" d=\"M5 11h3m16 0h3M5 22h4m14 0h4\"/>",
  coins:'<g fill="none" stroke-width="1.5"><path fill="currentColor" fill-opacity=".12" d="M16 3 23 5 28 10 29 17 26 24 20 28 12 29 6 25 3 19 3 12 8 6Z"/><path fill="currentColor" fill-opacity=".25" stroke="none" d="M27 11 27 18 24 24 18 27 11 27 6 23 9 27 16 30 24 27 29 20 30 14Z"/><path stroke-width="1.1" d="M10 8 16 6 23 9M7 12l-1 5 3 6M22 24l3-4"/><path fill="currentColor" stroke-width=".5" d="m9 11 4 3 3-6 3 6 4-3-2 10H11Z"/><path d="M12 24h8"/></g>',
  bag:'<path d="M10 9 7 3h18l-4 6M10 9c-2 5-7 7-7 14 0 8 26 8 26 0 0-7-5-9-8-14ZM9 10h13m-8 5-2 6m7-6 2 6"/>',
  forge:"<g fill=\"none\" stroke-width=\"1.5\"><path fill=\"currentColor\" fill-opacity=\".12\" d=\"m4 6 3-2 19 20 1 5-5-2Z\"/> <path fill=\"currentColor\" fill-opacity=\".25\" stroke=\"none\" d=\"m6 7 18 19 3 3-5-2L4 8Z\"/> <path fill=\"currentColor\" fill-opacity=\".12\" d=\"m16 11 4 4L7 30l-4-3Z\"/> <path fill=\"currentColor\" fill-opacity=\".25\" stroke=\"none\" d=\"m18 14 2 1L7 30l-2-2Z\"/> <path fill=\"currentColor\" fill-opacity=\".12\" d=\"m10 7 6-5 14 12-6 6Z\"/> <path fill=\"currentColor\" stroke-width=\".5\" d=\"m25 10 5 4-6 6-5-4Z\"/> <path stroke-width=\"1.1\" d=\"m13 8 9 8M15 6l5 4\"/></g>",
  check:'<path d="m6 16 6 6L27 7"/>',
  scroll:'<path d="M9 4h16c7 0 4 8 0 8H9M9 4C3 4 3 11 9 11v16h16V8M9 27H5c-4 0-3-6 1-6h14M12 15h9m-9 4h7"/>',
  plus:'<path d="M16 7v18M7 16h18"/>'
};
const renderGatehouseGearIcon=key=>`<svg class="tg-icon" viewBox="0 0 32 32" aria-hidden="true" focusable="false">${GATEHOUSE_GEAR_ICONS[key]||GATEHOUSE_GEAR_ICONS.scroll}</svg>`;
function renderGatehouseGearSlot(slot){return `<button type="button" class="tg-slot${slot.equipped?"":" is-empty"}" data-gear-slot="${slot.slot}" data-rarity="${escapeHtml(slot.equippedDefinition?.rarity||"")}" aria-pressed="${slot.isSelected}" aria-label="${escapeHtml(slot.label+(slot.equipped?`, ${slot.equippedDefinition.gearName}, Level ${slot.equipped.level}`:", empty"))}"><span class="tg-slot-art">${slot.equipped?renderGatehouseGearArt(slot.equippedDefinition.art):renderGatehouseGearIcon("plus")}</span><span>${slot.label}<small>${slot.equipped?"Lv. "+slot.equipped.level:"Empty"}</small></span>${slot.isUpgradeReady?'<b class="tg-ready" title="Matching upgrade material available">!</b>':""}</button>`;}
function renderGatehouseGearBagTile(group){const item=group.representative,def=group.definition;return `<button type="button" class="tg-item${group.isEquipped?" equipped":""}${group.isCompatible?" compatible":""}" data-gear-instance="${escapeHtml(group.representativeInstanceId)}" data-gear-stack-key="${escapeHtml(group.key)}" data-rarity="${escapeHtml(def.rarity)}" aria-pressed="${group.isSelected}" aria-label="${escapeHtml(`${def.gearName}, Level ${item.level}, ${group.count} owned${group.isEquipped?", equipped":""}${group.isNew?", new":""}`)}" title="${escapeHtml(def.gearName)}"><span class="tg-item-mark">${group.isEquipped?renderGatehouseGearIcon("check"):group.isNew?'<b>New</b>':""}</span>${renderGatehouseGearArt(def.art)}<span class="tg-item-level">Lv. ${item.level}</span>${group.count>1?`<span class="tg-item-count">×${group.count}</span>`:""}<span class="tg-item-name">${escapeHtml(getGatehouseGearShortName(def.gearName))}</span>${group.isUpgradeReady&&!group.isEquipped?'<b class="tg-ready" title="Matching upgrade material available">!</b>':""}</button>`;}
function renderGatehouseGearDetails(vm){
  if(!vm.selected)return `<section class="tg-details" aria-labelledby="tgDetailsTitle"><header class="tg-section-heading"><h3 id="tgDetailsTitle">Selected equipment</h3></header><div class="tg-empty"><span>${renderGatehouseGearIcon("scroll")}</span><h4>No ${escapeHtml(vm.selectedSlot)} gear selected</h4><p>Choose an equipped slot or an item from the Defensive Commander’s equipment bag.</p></div></section>`;
  const {selected:item,definition:def,requirement:req}=vm;
  const gold=state.gold,lowGold=req&&gold<vm.upgradeGold;
  const allowed=vm.canMerge&&!lowGold&&!vm.actionInFlight;
  return `<section class="tg-details" aria-labelledby="tgDetailsTitle">
    <header class="tg-section-heading"><h3 id="tgDetailsTitle">Selected equipment</h3><span>${item.isEquipped?"Equipped":"In bag"}</span></header>
    <div class="tg-detail-scroll" data-gear-panel="details" tabindex="0" aria-label="Item description and upgrade requirements">
      <div class="tg-item-hero"><div class="tg-inspected-art" data-rarity="${escapeHtml(def.rarity)}">${renderGatehouseGearArt(def.art)}</div><div><p class="tg-eyebrow">Defensive Commander’s</p><h4>${escapeHtml(getGatehouseGearShortName(def.gearName))}</h4><p class="tg-item-meta">${titleCaseCommonGearLabel(def.rarity)} · ${titleCaseCommonGearLabel(item.slot)} · Level ${item.level} / ${COMMON_GEAR.MAX_LEVEL}</p><div class="tg-levels" role="img" aria-label="Level ${item.level} of ${COMMON_GEAR.MAX_LEVEL}">${Array.from({length:COMMON_GEAR.MAX_LEVEL},(_,i)=>i+1).map(n=>`<i class="${n<=item.level?"filled":""}"></i>`).join("")}</div></div></div>
      <div class="tg-effect"><strong>+${formatGatehouseGearPercent(vm.currentBonus)}%</strong><span>${escapeHtml(titleCaseCommonGearLabel(def.statLabel))}</span></div>
      ${req?`<p class="tg-next">Next level <strong>+${formatGatehouseGearPercent(vm.nextBonus)}%</strong><span>+${formatGatehouseGearPercent(vm.nextBonusIncrease)}% increase</span></p>`:'<p class="tg-next">Maximum bonus reached</p>'}
      <div class="tg-requirements"><h5>${renderGatehouseGearIcon("forge")} ${req?"Upgrade to Level "+(item.level+1):`Level ${COMMON_GEAR.MAX_LEVEL} complete`}</h5>${req?`<dl><div><dt>Matching Level ${item.level} copy</dt><dd class="${vm.duplicateCount>=req.duplicates?"ready":"short"}">${vm.duplicateCount} / ${req.duplicates} available</dd></div><div><dt>Gold cost</dt><dd class="${lowGold?"short":""}">${formatGatehouseGearNumber(vm.upgradeGold)}</dd></div><div><dt>Raw production</dt><dd>${req.baseGoldHours} ${req.baseGoldHours===1?"hour":"hours"}</dd></div><div><dt>Your gold</dt><dd>${formatGatehouseGearNumber(gold)}</dd></div></dl>`:'<p>This item has reached its maximum level.</p>'}</div>
      ${lowGold?'<p class="tg-warning">Insufficient gold for this upgrade.</p>':vm.mergeReason&&req?`<p class="tg-warning">${escapeHtml(vm.mergeReason)}</p>`:""}
      <div class="tg-description"><h5>Item record</h5><p>${escapeHtml(vm.description)}</p><dl><div><dt>Officer</dt><dd>Defensive Commander</dd></div><div><dt>Category / slot</dt><dd>${titleCaseCommonGearLabel(def.category)} / ${titleCaseCommonGearLabel(item.slot)}</dd></div><div><dt>Binding</dt><dd>Not tradeable</dd></div><div><dt>State</dt><dd>${item.isEquipped?"Equipped":"In bag"}</dd></div><div><dt>Full Level ${vm.progressionLevel} path</dt><dd>${vm.progressionBaseCopies} Level 1 copies · ${vm.progressionGoldHours}h raw production</dd></div></dl></div>
    </div><footer class="tg-actions"><button class="tg-secondary" type="button" data-gear-equip ${vm.actionInFlight?"disabled":""}>${vm.actionInFlight?"Working…":item.isEquipped?"Unequip":"Equip"}</button><button class="tg-primary" type="button" data-gear-merge ${allowed?"":"disabled"}>${req?"Upgrade":"Max Level"}${req?renderGatehouseGearIcon("forge"):""}</button></footer>
  </section>`;
}

function renderGatehouseGearConfirmation(vm) {
  const { selected, definition, requirement } = vm;
  if (!vm.mergeConfirmOpen || !selected || !definition || !requirement) return "";
  return `<div class="tg-confirm-backdrop">
    <section class="tg-confirm" role="alertdialog" aria-modal="true" aria-labelledby="commonGearMergeTitle" aria-describedby="commonGearMergeCopy"><div>
      ${renderGatehouseGearIcon("forge")}<p class="tg-eyebrow">Gatehouse workshop</p>
      <h2 id="commonGearMergeTitle">Upgrade ${escapeHtml(getGatehouseGearShortName(definition.gearName))}?</h2>
      <div class="tg-combine"><span class="tg-confirm-art" data-rarity="${escapeHtml(definition.rarity)}">${renderGatehouseGearArt(definition.art)}</span><span>Level ${selected.level}<br>+ ${requirement.duplicates} matching copy</span><b aria-hidden="true">→</b><span>Level ${selected.level + 1}<strong>+${formatGatehouseGearPercent(vm.nextBonus)}%</strong></span></div>
      <p id="commonGearMergeCopy">Combine this Level ${selected.level} item with ${requirement.duplicates} unequipped matching Level ${selected.level} copy. Both inputs are consumed to create one new Level ${selected.level + 1} item.</p>
      <dl><div><dt>Gold cost</dt><dd>${formatGatehouseGearNumber(vm.upgradeGold)}</dd></div><div><dt>Raw production</dt><dd>${formatStackedBonusPercent(requirement.baseGoldHours)}h</dd></div></dl>
      <p class="tg-warning">This two-to-one upgrade cannot be undone.</p>
      <footer><button type="button" data-gear-merge-cancel>Cancel</button><button class="tg-primary" type="button" data-gear-merge-confirm ${vm.actionInFlight || !vm.canMerge ? "disabled" : ""}>Confirm Upgrade</button></footer>
    </div></section>
  </div>`;
}

function renderGatehouseGearScreen(vm) {
  const groups = vm.filteredBagGroups;
  return `<section class="tg-shell" data-common-gear-screen>
    <header class="tg-header" ${vm.mergeConfirmOpen?"inert":""}><div class="tg-seal">${renderGatehouseGearIcon("gatehouse")}</div><div class="tg-heading"><p>Inner Castle <span>· Defensive Commander</span></p><h2 id="tgTitle">Gatehouse</h2></div><div class="tg-gold">${renderGatehouseGearIcon("coins")}<span><small>Gold</small>${formatGatehouseGearNumber(state.gold)}</span></div><button type="button" class="tg-back" data-gear-back><span aria-hidden="true">←</span><span>Back to Inner Castle</span></button><span class="tg-close-space" aria-hidden="true"></span></header>
    <main class="tg-main" ${vm.mergeConfirmOpen?"inert":""}><section class="tg-loadout" aria-labelledby="tgOfficerTitle"><header class="tg-section-heading"><h3 id="tgOfficerTitle">Defensive Commander</h3><span>Equipment</span></header><div class="tg-loadout-grid"><div class="tg-slot-column">${vm.leftSlots.map(renderGatehouseGearSlot).join("")}</div><figure class="tg-officer"><img data-gatehouse-officer src="${GATEHOUSE_OFFICER_ART}" alt="Defensive Commander in worn steel and a moss-green cloak, resting a hand on a fortress shield" width="400" height="800" draggable="false" onerror="this.hidden=true"><figcaption>Warden of the walls</figcaption></figure><div class="tg-slot-column">${vm.rightSlots.map(renderGatehouseGearSlot).join("")}</div></div><footer class="tg-loadout-footer"><span>${vm.slots.filter(s=>s.equipped).length} / 8 slots equipped</span><span><b>!</b> Upgrade material ready</span></footer></section>
    <section class="tg-bag" aria-labelledby="tgBagTitle"><header class="tg-section-heading"><h3 id="tgBagTitle">${renderGatehouseGearIcon("bag")} Equipment Bag</h3><span>${vm.bagOwnedCount} owned</span></header><div class="tg-bag-controls"><label for="tgFilter">Show</label><select data-gear-bag-select id="tgFilter" aria-label="Filter equipment bag"><option value="all">All slots</option>${COMMON_GEAR.SLOTS.map(s=>`<option value="${s}" ${vm.bagFilter===s?"selected":""}>${titleCaseCommonGearLabel(s)}</option>`).join("")}</select></div><div class="tg-bag-scroll" data-gear-bag-scroll tabindex="0" aria-label="Equipment inventory"><div class="tg-items">${groups.map(renderGatehouseGearBagTile).join("")||`<div class="tg-empty"><h4>No equipment here</h4><p>${vm.instances.length?"Change the filter to see the Defensive Commander’s other gear.":"Open Common Gear Boxes to find gear for the Defensive Commander."}</p></div>`}</div></div><footer class="tg-bag-footer"><span>${groups.length} shown · ${vm.bagStackCount} stacks</span><span>${renderGatehouseGearIcon("check")} Equipped <b class="tg-legend-ready">!</b> Ready</span></footer></section>
    ${renderGatehouseGearDetails(vm)}</main>${renderGatehouseGearConfirmation(vm)}</section>`;
}
