[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/Crownlands-current-build"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/Crownlands-current-build/"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/Crownlands-current-build/*"
  to = "/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/firebase-hosting-redirect"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/firebase-hosting-redirect/*"
  to = "/"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache"
